### ISSUE TITLE
Safely quit game

### ISSUE THREAD

**Issue by ghost** [zmarcos/godothreadpool#11]
Great addon. 👍 But how to safely quit the game when threads are running? For example when clicked on X (Windows) or call `get_tree().quit()`. Is there a way to prevent quit until all threads are shutdown? Otherwise I get random errors. E.g. stuff becomes null, because already destroyed. etc.

**Comment by zmarcos** [comment]
Thanks 😊!
When the **ThreadPool** node is destroyed, it receives the `NOTIFICATION_PREDELETE` notification, and the function `__wait_for_shutdown()` is called.
Function `__wait_for_shutdown(`) will shutdown the pool and wait for all tasks to finish.

Here is what could be wrong, with probabilities included (they are 99% trustworth, trust me bro):
- 98.99% The game developer is violating **"the contract"** (when a thread is reading or writing something, other threads should NOT touch it, specially the main thread). When sending work to the pool, please do not pass nodes that are already in the scene, because the main thread can control them, and will destroy them when another thread is reading\writing. 
- 1% This is a bug in the `ThreadPool` class, the function  `__wait_for_shutdown()` is not being called. Please let me know if this happens to you, specify the Godot version, OS, and any other detail you think is useful.
- 0.01% This a bug in Godot itself.

BONUS:
There is a workaround fix, calling `my_game_thread_pool.__wait_for_shutdown()` before every `get_tree().quit()` and writing a `NOTIFICATION_WM_CLOSE_REQUEST` notification handler to do it. But if you are violating **"the contract"**, eventually your players will find worse bugs for you, your game state will get silently corrupted over time.

**Comment by ghost** [comment]
The method ` __wait_for_shutdown` is called. But I think the problem is that the quit process does not wait for anything. 

```gdscript
func _ready():
  get_tree().set_auto_accept_quit(false)

func _notification(what):
  if what == NOTIFICATION_WM_CLOSE_REQUEST:
    Threads.__wait_for_shutdown()
    get_tree().quit()

```

[Docs: Handling Quit Requests](https://docs.godotengine.org/en/stable/tutorials/inputs/handling_quit_requests.html)

That works. The plugin could provide this method as public name (without `__`) for that use case. I would not implement `set_auto_accept_quit` in the plugin. Because the developer should control it.
