### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by tavurth** [zmarcos/godothreadpool#5]
This library looks promising and I was hoping to replace my thread library with it but sadly it's taking too much time to comb through the code trying to figure out how to await a custom future implementation.

Perhaps you'd have some time to explain here the basics and I could make a PR to update the documentation based on your responses?

**Comment by zmarcos** [comment]
I did plan to add a small project to show how a [ThreadPool](https://github.com/zmarcos/godothreadpool/wiki/ThreadPool) is expected to be used, but not for [FutureThreadPool](https://github.com/zmarcos/godothreadpool/wiki/FutureThreadPool).

## Because:

1. few people use it
2. needs a bit more discipline from the developer to be used effectively
3. at the time (2020) didn't play nice on the web with multi-threading disabled (still true, but at least we can enable multi-threading now)

## Anyway, this is the basics:

1. never wait for something in the main thread 
2. one **future** to rule them all, one **future** to bring them all and in the darkness bind them

## How you can make it work:
have a global var somewhere in the scene to hold the task:
```gdscript
var myBigFuture: FutureThreadPool.Future
```
then you can create a future like this:
```gdscript
myBigFuture = myFutureThreadPool.submit_task(myGameMechanic, "game_loop", 22)
```
now inside your function, you can do this:
```gdscript
func game_loop(a_number):
  	var sub_task_future1: FutureThreadPool.Future = myFutureThreadPool.submit_task(myGameData, "do_something_cool", 1)
  	var sub_task_future2: FutureThreadPool.Future = myFutureThreadPool.submit_task(myGameData, "calculate_important_value", 2)
  	var sub_task_future3: FutureThreadPool.Future = myFutureThreadPool.submit_task(myGameData, "do_a_long_calculation", 3)
  	do_something_unrelated_to_everything_else()
  	sub_task_future1.wait_for_result() 
  	do_something_that_needs_to_happen_after_task1()
  	return sub_task_future2.get_result() + sub_task_future3.get_result()
```

now, somewhere in your scene you need to query the future (never call `get_result()` or `wait_for_result()`)
```gdscript
func _process (delta):
  	if myBigFuture.finished:
  	  	if myBigFuture.completed:
  	  	  	show_to_the_player();
  	  	  else:
  	  	  	send_error_report_to_the_developer()
```
You can also use signals.

I know, I know, this could be in the documentation, feel free to make a PR.
I'm not working with Godot currently 😞, so I only update things on request.

**Comment by zmarcos** [comment]
We use **GDScript documentation comments** now, if you find any new issue, feel free to collaborate.
